### ISSUE TITLE
Homepage link on PyPI invalid

### ISSUE THREAD

**Issue by njanakiev** [JoaoCarabetta/s2-py#1]
Thanks for the great project to understand the s2 index. I noticed that the Homepage link on https://pypi.org/project/s2/ is not pointing to this repository, but instead to https://github.com/JoaoCarabetta/s2

**Comment by JoaoCarabetta** [comment]
Hi @njanakiev, thanks for the heads up.

I just merged this project to [BabelGrid](https://github.com/EL-BID/BabelGrid).

It supports more grid types and has some cool functionalities. Check it out.
